language: android
android:
        components:
                - platform-tools
                - build-tools-25.0.3
                - android-25
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
group: deprecated-2017Q4           
