language: android
android:
  components:
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-m2repository
script:
- "./gradlew build"
before_install:
- chmod +x gradlew
branches:
  only:
  - master
group: deprecated-2017Q4
notifications:
  slack:
    on_success: always
env:
  global:
     secure: "nzuXhm4bskuzKIFicOCuxPNppLwXBRUpnFjHZMaL7Z5x9B8aQUwgHyG+nEaEerJSKOpwCNeJqDmiTEhfXNsFWgkR4mOueIpydEt8e4kpLs22cJ0AYemDhWrzvyz5OYThsnEQeWy2ny3SCppmEoiaHkp33HyJNHxRY+HWR0MIEQNodTijcrpEoJLtcsD1nGYhZ4S60mOOPktA3iieDNKf0IythaS9qO0Epbr8v5PO6PPiZc0IV/zaoGG1wsFQz1vM1OysUdKEbyDRP6KjywcqIQKWpCYSDpmIKCgXRvM6MgSVL7e+DVhMoJKuYPklLiQrf/vqJCiQSEpexMJcSCfKFFOA4JKOjf9RQVlAX6KcKjoSLVo3qNSG35ddKQd7GfeTtVe2TNVAajTx1CsKxmSkWGr+lWiXTAtgkcnKwv2JbGzvBmBd7qgUyfhkqt/GmofX+xezu9yP4rtIWYungHROW74DeKvtlrxvJACiXbySCqI6BO/ECS4np1ngnA/EWKhEiU5v+B9aVQ4+Gih0FX+4OCtKO5Q7CLvikI4+wP7KGEhcYGJB5JQVVy1WzEOZFpc+cJzc/xkfJpJYEnYHjFuR11lmp/dp6eUYLq2OU15cMA4BFuZGHVcGuO3CmFCgkeQy/rde583SU10bBFj4uZTxeB3/0b4nzf9RSq7BGq0t4P8="

